baseURL = "https://hee-san.github.io/blog"
languageCode = "en-us"
title = "へーさんのブログ"

publishDir = "docs"

theme = "jeffprod"
googleAnalytics = "UA-114441596-3"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"

# Twitter card config
# Enable with this.
twitterCardEnabled = true
# Don't include the @.
# twitterCardSite =
twitterCardDomain = "budougumi0617.github.io"
# Don't include the @.
twitterCardAuthor = "budougumi0617"
