baseURL = "https://hee-san.github.io/blog"
languageCode = "en-us"
title = "へーさんのブログ"

publishDir = "docs"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
