baseURL = "https://hee-san.github.io/blog/"
languageCode = "en-us"
title = "へーさんのブログ"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"
